repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: pretty-format-json
      args: ['--no-sort-keys','--autofix']
      language_version: python3.11

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: [--line-length=100, --fast]
      language_version: python3.11

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy
      language_version: python3.11

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions'
     ]
      language_version: python3.11
      args:
      - --extend-ignore=D104,B011,D100,D200,D101,D401,D202
      - --max-line-length=100
      - --per-file-ignores=tests/** :D103,D100
